### ISSUE TITLE
Error: write EPIPE

### ISSUE THREAD

**Issue by pashoo2** [bakunin95/wavi#2]
Hello!
I've got an error:
/usr/bin/node wavi.js
finished HTML analysis...
finished js analysis...
finished misc analysis...
update element ids...
generating graph (could take several minutes)...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:904:11)
    at Object.afterWrite (net.js:720:19)
I've tried to do it with a root permissions, and it's not solved the problem.

**Comment by bakunin95** [comment]
Hi,
Ok, looking at the error all the data get extracted from the web app but Graphviz fail to generate the graph. You can try a different extension ex: svg, png, pdf. or upgrade graphviz but im not sure that will fix it. Im going to work on that issue and release a new version this week.

**Comment by pashoo2** [comment]
Thank's. I'll be waiting a resolution

**Comment by bakunin95** [comment]
I have publish a new version, you can try it:

npm uninstall wavi -g
npm cache clean
npm install wavi -g

Im going to test it on ubuntu tomorrow, what graphviz version do you have ?

**Comment by ergose** [comment]
I have the same issue, but mine says 718:19 instead of 720:19 and 901:11 instead of 904:11. I have installed 0.2.10.

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:901:11)
    at Object.afterWrite (net.js:718:19)
```

I ran into it after having trouble getting it to work at the command line. I installed it globally with sudo on Ubuntu 14.04. Originally I was getting: `: No such file or directory` when I would run `wavi --svg jade jade_uml/jade.svg`. When I did `node /usr/local/bin/wavi --svg jade jade_uml/jade.svg` then it actually tried, but then I got the above error. There are also a few "Unexpected token" lines and a "Illegal return statement" from where it's going through the files above the final error, but it does reach "generating graph". 

Thanks for working on this. I'm very visual, so even a partial image of a programs structure usually helps. Sketching UML on printer paper gets old. :smile:

**Comment by bakunin95** [comment]
Ok, i developped it on windows, that error seems linux specific so i just installed ubuntu and saw the first problem, it look like a path problem ill work on a fix, and hopefully i find the second problem.

**Comment by bakunin95** [comment]
I found the first problem, ubuntu package is now called nodejs to avoid confusion and explain why node is not found.
http://stackoverflow.com/questions/18130164/nodejs-vs-node-on-ubuntu-12-04

You can do the following:
sudo apt-get install nodejs-legacy

then:

npm uninstall wavi -g
npm install wavi -g

node /usr/local/bin/wavi --svg ./jade ./jade.png

About the second problem, does "jade_uml" folder exist before you run the script ?

Unexpected token error are when JavaScript is parsed, the analyzer can't make sens of the code, either there is a bug in it or its valid but only at execution for example a variable that has been instanciated in another file is being used and the analyzer just doesn't know what it is because it analyze each file separatly.

**Comment by ergose** [comment]
Sorry it took so long to get back. I just uninstalled and then re-installed it. The unexpected token error still showed up and was nagging on me. Then I noticed that the files that are throwing the errors are in either a test/cases directory, a bin directory, and a doc directory. I checked the bin one and it looks like the part throwing the error is minified. I suspect if I could omit the directories then it would work. Can I pass it directories to ignore?

**Comment by ergose** [comment]
Well, I moved the directories with the problem files completely out and there were no more unexpected token errors. I thought it was going to work, but this is what I got: 

```
$ node /usr/local/bin/wavi --svg ./jade ./jade.png
finished HTML analysis...
finished js analysis...
finished java analysis...
finished misc analysis...
update element ids...
generating graph (could take several minutes)...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:901:11)
    at Object.afterWrite (net.js:718:19)
```

**Comment by bakunin95** [comment]
Can you do this command: sfdp -V 
This will give the exact version of graphviz so i can test it, also is your project open source ? i could run it with wavi and send you the result.

**Comment by brenopolanski** [comment]
Hey @ergose and @bakunin95 

I solved just with installing the **graphviz**

my version: sfdp - graphviz version 2.36.0 (20140111.2315)

**Comment by ergose** [comment]
@brenopolanski - I think that did it. :) The project I was trying to get a visual of didn't throw errors, but it also didn't make an image. I tried it with a different project though and got a graph fine, so any odd stuff is probably on my box from here on. Thanks.
